Repository chshersh/github-tui, pull requests merged in 2025-01, with the labels that each got.

#13 Rewrite the TUI framework
  .github/workflows/ci.yml
  .ocamlformat
  dune-project
  github_tui.opam
  github_tui.opam.template
  lib/cli.ml
  lib/fs/fs.mli
  lib/log/dune
  lib/log/log.ml
  lib/log/log.mli
  lib/pretty/chunk.mli
  lib/pretty/line.mli
  lib/pretty/pretty.mli
  lib/shell/shell.mli
  lib/tui/dune
  lib/tui/init.ml
  lib/tui/tea/dune
  lib/tui/tea/key.ml
  lib/tui/tea/key.mli
  lib/tui/tea/stdin.ml
  lib/tui/tea/stdin.mli
  lib/tui/tea/tea.ml
  lib/tui/tea/tea.mli
  lib/tui/tui.ml
  lib/tui/tui.mli
  lib/tui/update.ml
  lib/tui/widget.ml
Labels: component: performance, priority: high

#11 Check for binary file warning and don't print
  lib/fs/dune
  lib/fs/fs.ml
Labels: component: UI

#15 Use binary icon for binary file types
  lib/fs/fs.ml
  lib/fs/fs.mli
  lib/tui/widget.ml
Labels: type: feature, component: UI

#22 Switch to setup-ocaml@v3
  .github/workflows/ci.yml
Labels: type: bug, component: DX, priority: high

#19 Lazify dir reading
  lib/fs/fs.ml
  lib/fs/fs.mli
  lib/tui/tui.ml
  lib/tui/widget.ml
Labels: type: refactoring, component: performance

#20 Move file content stuff into a filec module in Fs
  lib/fs/filec.ml
  lib/fs/filec.mli
  lib/fs/fs.ml
  lib/fs/fs.mli
  lib/tui/widget.ml
Labels: type: refactoring, component: DX

#21 Refactor up/down moves
  lib/fs/fs.ml
Labels: type: refactoring, component: DX

#26 Implement pretty issue rendering
  lib/gh/issue.ml
  lib/gh/issue.mli
  lib/pretty/color.ml
  lib/pretty/color.mli
  lib/pretty/pretty.ml
  lib/pretty/pretty.mli
  lib/pretty/style.ml
  lib/tui/view.ml
Labels: type: feature, component: UI, component: GH

#27 Add first tests (for colors)
  dune-project
  github_tui.opam
  lib/pretty/color.ml
  lib/pretty/color.mli
  test/dune
  test/test.ml
  test/test_extra/dune
  test/test_extra/test_extra.ml
  test/test_extra/testable.ml
  test/test_github_tui.ml
  test/test_pretty/dune
  test/test_pretty/test_color.ml
  test/test_pretty/test_pretty.ml
Labels: component: DX, type: test

#30 Refactor file type check (lazy and only 1024 bytes)
  lib/fs/filec.ml
  lib/fs/filec.mli
  lib/fs/fs.ml
  lib/fs/fs.mli
  lib/tui/tui.ml
  lib/tui/widget/code.ml
Labels: type: refactoring, component: performance

#33 Implement terminal size warning
  lib/cli.ml
  lib/tui/tui.ml
  lib/tui/tui.mli
Labels: type: feature, component: UI

#34 Implement invalid GITHUB_TOKEN handling
  lib/gh/client.ml
  lib/gh/client.mli
  lib/gh/issue.ml
  lib/gh/issue.mli
  lib/gh/pr.ml
  lib/gh/pr.mli
  lib/tui/model/issue.ml
  lib/tui/model/issue.mli
  lib/tui/model/model.ml
  lib/tui/model/pr.ml
  lib/tui/update.ml
  lib/tui/widget/issue.ml
  lib/tui/widget/pr.ml
  lib/tui/widget/pr.mli
Labels: component: UI, type: refactoring, component: GH
