Repository chshersh/github-tui, pull requests merged in 2025-02, with the labels that each got.

#38 Reduce duplication for displaying GitHub API errors
  lib/tui/widget/common.ml
  lib/tui/widget/common.mli
  lib/tui/widget/issue.ml
  lib/tui/widget/pr.ml
Labels: type: refactoring, component: DX

#41 Refactor horizontal rendering slightly
  lib/extra/list_extra.ml
  lib/extra/list_extra.mli
  lib/pretty/doc.ml
Labels: type: refactoring, component: performance

#44 Send warnings to the standard error
  lib/tui/tui.ml
Labels: type: refactoring, component: chore

#42 Handle invalid GitHub token
  lib/gh/client.ml
  lib/gh/client.mli
  lib/tui/widget/common.ml
Labels: type: feature, component: UI

#45 Add Code of Conduct and Contributing guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: component: documentation, type: feature, priority: high

#47 Refactor unnecessary code in Client.query
  lib/gh/client.ml
Labels: type: refactoring

#51 Move all the icons into Pretty.Icon
  lib/pretty/icon.ml
  lib/pretty/pretty.ml
  lib/pretty/pretty.mli
  lib/tui/render/render.ml
  lib/tui/widget/code.ml
  lib/tui/widget/common.ml
  lib/tui/widget/generic.ml
  lib/tui/widget/pr.ml
Labels: component: UI, type: refactoring

#52 Refactor file tree type
  lib/fs/fs.ml
  lib/fs/fs.mli
  lib/tui/tui.ml
  lib/tui/widget/code.ml
Labels: type: refactoring, component: chore

#54 Refactor init
  lib/cli.ml
  lib/tui/dune
  lib/tui/init/dune
  lib/tui/init/init.ml
  lib/tui/init/init.mli
  lib/tui/tui.ml
  lib/tui/tui.mli
Labels: type: refactoring, component: chore

#56 GH-55: Provide a better error message in case of failure while cloning the repository
  lib/shell/shell.ml
  lib/shell/shell.mli
  lib/tui/init/init.ml
Labels: type: bug, component: UI
